
apiVersion: v1
kind: ConfigMap
metadata:
  name: cinebooker-config
  namespace: cinebooker
data:
  nginx.conf: |
    server {
      listen 80;
      
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html =404;
      }
      
      # Add special handling for metrics endpoint
      location /api/metrics {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
        add_header Content-Type text/plain;
      }
    }
