
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cinebooker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/cinebooker.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: cinebooker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
